version: '3'
services:
  web:
    build: .
    volumes:
      - ./lambda_aws:/home/hosting
      - ~/.ssh:/home/hosting/.ssh
      - lambda_rvm:/home/hosting/.rvm
    stdin_open: true
    tty: true
volumes:
  lambda_rvm:
