version: '3'
services:
  web:
    build: .
    volumes:
      - /Users/jwozniak/praca/projekty/lambda_aws:/home/hosting
      - /Users/jwozniak/.ssh:/home/hosting/.ssh
      - lambda_rvm:/home/hosting/.rvm
    stdin_open: true
    tty: true
volumes:
  lambda_rvm:
